# Generated by Django 2.1.4 on 2018-12-11 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oportunidaderecentes',
            name='cod_projeto',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='oportunidaderecentes',
            name='descricao',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='oportunidaderecentes',
            name='nome',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='ordensdeservico',
            name='numero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='piac.OportunidadeRecentes'),
        ),
        migrations.AlterField(
            model_name='ordensdeservico',
            name='recursos',
            field=models.ManyToManyField(default='', editable=False, to='planningBoard.Funcionario'),
        ),
    ]
