# Generated by Django 2.1.4 on 2018-12-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piac', '0002_auto_20181211_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordensdeservico',
            name='recursos',
            field=models.ManyToManyField(to='planningBoard.Funcionario'),
        ),
    ]
