# Generated by Django 2.1.4 on 2018-12-11 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piac', '0003_auto_20181211_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordensdeservico',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='ordensdeservico',
            name='recursos',
        ),
        migrations.DeleteModel(
            name='OportunidadeRecentes',
        ),
        migrations.DeleteModel(
            name='OrdensDeServico',
        ),
    ]
