# Generated by Django 2.1.4 on 2018-12-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('piac', '0004_auto_20181211_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='OportunidadeRecentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('cod_projeto', models.CharField(max_length=30)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('SR', 'Serviço'), ('PJ', 'Projeto')], default='Serviço', max_length=2)),
            ],
        ),
    ]
