# Generated by Django 2.1.4 on 2018-12-11 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planningBoard', '0001_initial'),
        ('piac', '0005_oportunidaderecentes'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdensDeServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jsa_status', models.BooleanField(default=False)),
                ('crol_status', models.BooleanField(default=False)),
                ('rels_status', models.BooleanField(default=False)),
                ('reld_status', models.BooleanField(default=False)),
                ('gpg_status', models.BooleanField(default=False)),
                ('mobile_status', models.BooleanField(default=False)),
                ('numero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piac.OportunidadeRecentes')),
                ('recursos', models.ManyToManyField(to='planningBoard.Funcionario')),
            ],
        ),
    ]
