# Generated by Django 2.1.4 on 2018-12-14 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piac', '0006_ordensdeservico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordensdeservico',
            name='recursos',
            field=models.ManyToManyField(blank=True, null=True, to='planningBoard.Funcionario'),
        ),
    ]
