# Generated by Django 2.1.4 on 2018-12-14 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piac', '0007_auto_20181214_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordensdeservico',
            name='id',
        ),
        migrations.AlterField(
            model_name='ordensdeservico',
            name='numero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='piac.OportunidadeRecentes'),
        ),
    ]
