# Generated by Django 2.1.4 on 2018-12-14 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piac', '0008_auto_20181214_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordensdeservico',
            name='numero',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='piac.OportunidadeRecentes'),
        ),
    ]
