# Generated by Django 2.1.4 on 2018-12-14 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piac', '0009_auto_20181214_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordensdeservico',
            name='recursos',
            field=models.ManyToManyField(to='planningBoard.Funcionario'),
        ),
    ]
