# Generated by Django 2.1.4 on 2018-12-14 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piac', '0010_auto_20181214_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordensdeservico',
            name='numero',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='numero', serialize=False, to='piac.OportunidadeRecentes'),
        ),
    ]
