# Generated by Django 2.1.4 on 2018-12-14 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piac', '0014_auto_20181214_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordensdeservico',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ordensdeservico',
            name='numero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piac.OportunidadeRecentes', unique=True),
        ),
    ]
