# Generated by Django 2.1.4 on 2018-12-14 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piac', '0015_auto_20181214_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordensdeservico',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
